cam_res = "qqvga"
cam_format = "yuv"

debug_frag_udp_cam = false

ip_addr_esp = "192.168.4.1"

udp_port_ctrl = 3333
udp_port_sensors = 34254
udp_port_vid = 34255
udp_port_dump = 34256
udp_port_logs = 34257